//! Build script for `memstroy-gui`.
//!
//! Bakes two compile-time signals into the binary:
//!
//! * **`default_server_url()`** — base URL of the
//!   `memstroy-assets-server` instance the editor connects to on
//!   first launch. Set `MEMSTROY_DEFAULT_SERVER_URL` when packaging
//!   for clients (e.g. `https://assets.your-domain.example`); when
//!   unset (developer builds), the loopback default
//!   `http://127.0.0.1:8765` is used.
//! * **`IS_CLIENT_BUILD`** — `true` iff `MEMSTROY_CLIENT_BUILD` is set
//!   to a truthy value (`1`, `true`, `yes`, `on`). The runtime uses
//!   this flag to switch between developer defaults (cwd-relative
//!   `./assets/`, in-process assets-server bootstrap) and
//!   client-distribution defaults (per-user cache directory, no
//!   in-process server — assets come exclusively from the remote one).
//!
//! Both values are emitted into `$OUT_DIR/build_info.rs` and pulled
//! into the crate via `src/build_info.rs`. The server URL is wrapped
//! through `obfstr::obfstr!` so it does not appear verbatim in
//! `strings(1)` on the shipped binary.

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-env-changed=MEMSTROY_DEFAULT_SERVER_URL");
    println!("cargo:rerun-if-env-changed=MEMSTROY_CLIENT_BUILD");

    let server_url = env::var("MEMSTROY_DEFAULT_SERVER_URL")
        .unwrap_or_else(|_| "http://127.0.0.1:8765".to_string());

    let is_client = matches!(
        env::var("MEMSTROY_CLIENT_BUILD").as_deref(),
        Ok("1") | Ok("true") | Ok("yes") | Ok("on") | Ok("TRUE") | Ok("YES") | Ok("ON"),
    );

    // Rust's `Debug` impl for `&str` produces a syntactically valid
    // escaped string literal (with surrounding quotes), which is
    // exactly what we need to splice into a generated source file.
    let url_literal = format!("{:?}", server_url);

    let generated = format!(
        "// AUTO-GENERATED by build.rs — do not edit.\n\
         //\n\
         // The server URL passes through `obfstr::obfstr!` so its\n\
         // literal bytes are XOR-encoded in the binary instead of\n\
         // sitting in the read-only data segment in plain ASCII.\n\
         // Decoded once at startup, then cached on `EditorState`.\n\
         pub fn default_server_url() -> String {{\n\
        \x20   obfstr::obfstr!({url_literal}).to_string()\n\
         }}\n\
         \n\
         /// `true` when this binary was produced with\n\
         /// `MEMSTROY_CLIENT_BUILD=1` set in the build environment.\n\
         /// Drives the cwd-vs-cache asset-root choice and whether the\n\
         /// editor auto-spawns an in-process assets-server.\n\
         pub const IS_CLIENT_BUILD: bool = {is_client};\n",
    );

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR is set by cargo");
    let dest = Path::new(&out_dir).join("build_info.rs");
    fs::write(dest, generated).expect("write build_info.rs");
}
